<template>
<el-table
    :data="tableData"
    border
    style="width: 100%">
    <el-table-column
      prop="date"
      label="序号"
      width="100">
    </el-table-column>
    <el-table-column
      prop="name"
      label="项目名称"
      width="250">
    </el-table-column>
    <el-table-column
      prop="address"
      label="企业名称">
    </el-table-column>
    <el-table-column
      prop="date"
      label="工作室名称"
      width="180">
    </el-table-column>
    <el-table-column
      prop="date"
      label="定金"
      width="120">
    </el-table-column>
    <el-table-column
      prop="date"
      label="定金支付情况"
      width="150">
    </el-table-column>
    <el-table-column
      prop="date"
      label="尾款"
      width="120">
    </el-table-column>
    <el-table-column
      prop="date"
      label="尾款支付情况"
      width="150">
    </el-table-column>
  </el-table>
</template>